---
title: "TaskA"
author: "zerofrom"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  latex_engine: xelatex
  pdf_document: null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Stat2Data)
library(dplyr)
```

# Q1. Data Wrangling
```{r}
setwd(getwd())
debt_df <- read.csv("debt_data.csv", header = TRUE, sep = ",")
country_df <- read.csv("country_data.csv", header = TRUE, sep = ",")
indicator_df <- read.csv("indicator_data.csv", header = TRUE, sep = ",")
#head(debt_df)
#summary(debt_df)
numCol = ncol(debt_df)
numRow = nrow(debt_df)
print(paste("debt_df: The number of columns: ",numCol))
print(paste("debt_df: The number of rows: ",numRow))
```
# Q2.Update data frame by reordering
```{r}
# reordering by the column 'DT.NFL.BLAT.CD'    
debt_df <- debt_df %>%
  arrange(desc(DT.NFL.BLAT.CD))
# select the specifed columns and display the first 4 rows
debt_df_sub <- debt_df %>%
  select("Country.Code", "Year", "NY.GNP.MKTP.CD", "DT.NFL.BLAT.CD") %>%
  head(4)
debt_df_sub
```

# Q3. Create debt_df2 and replace indicator column names in debt_df by referring to indicator_df
```{r}
column_mapping <-setNames(indicator_df$INDICATOR_NAME, indicator_df$INDICATOR_CODE)
column_mapping[c("Country.Code", "Year")] <- c("Country.Code", "Year")
debt_df2 <- debt_df %>%
  rename_with(~column_mapping[.x],.cols = names(debt_df)) 
debt_df2_sub <- debt_df2 %>%
  select("Country.Code","Year","Net financial flows, others (NFL, current US$)") %>%
  head(5)
debt_df2_sub
```

# Q4. Combine two data frames: debt_df and country_df
```{r}
country_df_select <- country_df %>%
  select("Country.Code","Region","IncomeGroup","Country.Name")
debt_df3 <- debt_df2 %>%
  left_join(country_df_select, by = "Country.Code")
# ncol2=ncol(debt_df2)
# ncol3=ncol(debt_df3)
# print(paste("debt_df2:The number of columns:", ncol2))
# print(paste("debt_df3:The number of columns:", ncol3))
debt_df3_sub <- debt_df3 %>%
  select("Country.Name","IncomeGroup", "Year", "Total reserves in months of imports") %>%
  head(3)
debt_df3_sub
```

# Q5. Rename 5 columns from their original names to the new names
```{r}
debt_df3 <- debt_df3 %>%
  rename(
    Total_reserves = 'Total reserves in months of imports',
    External_debt = 'External debt stocks, total (DOD, current US$)',
    Financial_flow = 'Net financial flows, bilateral (NFL, current US$)',
    Imports = 'Imports of goods, services and primary income (BoP, current US$)',
    IFC = 'IFC, private nonguaranteed (NFL, US$)'
  )
debt_df3_sub2 <- debt_df3 %>%
  select('Country.Code','Year','Total_reserves','External_debt','Financial_flow','Imports','IFC') %>%
  head(5)
debt_df3_sub2
```

# Q6. Create debt_summary
```{r}

```