---
title: "TaskB1"
author: "zerofrom"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## B.1     
### (1) Value of a
Considering chat $x$ follows the probability density function:

$$
p_{\lambda}(x)= \begin{cases}a e^{-\frac{b}{h}(x-1)} & \text { if } x \geqslant b,  \tag{1}\\ 0 & \text { if } x<b,\end{cases}
$$

The probability density function $p_{\lambda}(x)$ must follows:

$$
\begin{equation*}
\int_{-\infty}^{\infty} p_{\lambda}(x) d x=1 \tag{2}
\end{equation*}
$$

Since $p_{\lambda}(x)=0$ when $x<b$, it follows that:

$$
\begin{equation*}
\int_{b}^{\infty} p_{\lambda}(x) d x=1 \tag{3}
\end{equation*}
$$

Replacing expression (1) into expression (3) yields:

$$
\begin{equation*}
\int_{b}^{\infty} a e^{-\lambda(x-b)} d x=1 \tag{4}
\end{equation*}
$$

Assuming that $u=x-b$, it can be obtained that:

$$
\begin{equation*}
x=u+b, d x=d u \tag{5}
\end{equation*}
$$

Assuming that $x=b$, then $u=0$, therefore the upper and lower limits of integration become $0 \rightarrow \infty$, substituting expression $(s)$ :

$$
\begin{equation*}
\int_{0}^{\infty} a e^{-\lambda u} d u=1 \tag{6}
\end{equation*}
$$

Using the exponential integration formula:

$$
\begin{equation*}
\int_{0}^{\infty} e^{-a u} d u=\frac{1}{a} \tag{7}
\end{equation*}
$$

Thus:

$$
\begin{equation*}
a \cdot \frac{1}{\pi}=1 \tag{8}
\end{equation*}
$$

The solution is:

$$
\begin{equation*}
a=\frac{1}{\lambda} \tag{9}
\end{equation*}
$$

### In conclusion, the value of a is $\frac{1}{\lambda}$.      


#### (2) i) Population Mean $E[X]$ :

From the definition of the mean, there is:

$$
\begin{equation*}
E[x]=\int_{-\infty}^{\infty} x \cdot p_{n}(x) d x \tag{1}
\end{equation*}
$$

Replacing $p_{\lambda}(x)$ and $a=\lambda$ :

$$
\begin{equation*}
E[x]=\int_{b}^{\infty} x \cdot \lambda e^{-\lambda(x-b)} d x \tag{2}
\end{equation*}
$$

Assuming $u=x-b$, then $x=u+b$, and $d x=d u$ :

$$
\begin{align*}
E[X] &= \int_{0}^{\infty}(u + b) \cdot \lambda e^{-\lambda u} \, du \\
     &= \lambda \cdot \int_{0}^{\infty} u e^{-\lambda u} \, du + \lambda b \int_{0}^{\infty} e^{-\lambda u} \, du \tag{3}
\end{align*}
$$

Integral formula for exponential functions:

$$
\begin{equation*}
\int_{0}^{\infty} e^{-a x} d x=\frac{1}{a}, \int_{0}^{\infty} x e^{-a x} d x=\frac{1}{a^{2}} \tag{4}
\end{equation*}
$$

Replacing expression (t) into expression (3), there is:

$$
\begin{aligned}
E[x] & =\lambda \cdot \frac{1}{\lambda^{2}}+\lambda b \cdot \frac{1}{\lambda} \\
& =\frac{1}{\lambda}+b
\end{aligned}
$$

### In conclusion, the population mean $E[x]=\frac{1}{\lambda}+b$.    

#### ii) Standard Deviation $\sigma x$ :

The standard deviation formula:

$$
\begin{equation*}
\sigma x=\sqrt{\operatorname{Var}(x)}=\sqrt{E\left[x^{2}\right]-(E[x])^{2}} \tag{1}
\end{equation*}
$$

From the derivation of $E[x]$, it follows that:

$$
E[x]=\frac{1}{\lambda}+b \tag{2}
$$

The formula for $E\left[x^{2}\right]$ is:

$$
\begin{equation*}
E\left[x^{2}\right]=\int_{b}^{\infty} x^{2} \cdot p_{\lambda}(x) d x \tag{3}
\end{equation*}
$$

Substituting $P_{\lambda}(x)$ :

$$
\begin{equation*}
E\left[x^{2}\right]=\int_{b}^{\infty} x^{2} \cdot \lambda e^{-\lambda(x-b)} d x \tag{4}
\end{equation*}
$$

Assuming $u=x-b$. then $x=u+b$, and $d x=d u$ :

$$
\begin{align*}
E\left[x^{2}\right]= & \int_{0}^{\infty}(u+b)^{2} \cdot \lambda e^{-\lambda u} d u \\
= & \lambda \int_{0}^{\infty}\left(u^{2}+2 b u+b^{2}\right) \cdot e^{-\lambda u} d u \\
= & \lambda \int_{0}^{\infty} u^{2} e^{-\lambda u} d u+2 \lambda b \int_{0}^{\infty} u e^{-\lambda u} d u \\
& +\lambda b^{2} \int_{0}^{\infty} e^{-\lambda u} d u \quad \text { (t) } \tag{5}
\end{align*}
$$

Integrals formula for exponential functions:

$$
\begin{align*}
& \int_{0}^{\infty} e^{-a x} d x=\frac{1}{a} \\
& \int_{0}^{\infty} x e^{-a x} d x=\frac{1}{a^{2}} \\
& \int_{0}^{\infty} x^{2} e^{-a x} d x=\frac{2}{a^{3}} \tag{6}
\end{align*}
$$

Replacing formulas (6) into expression (5), there is:

$$
\begin{align*}
E\left[x^{2}\right] & =\lambda \cdot \frac{2}{\lambda^{3}}+2 \lambda b \cdot \frac{1}{\lambda^{2}}+\lambda b^{2} \cdot \frac{1}{\lambda} \\
& =\frac{2}{\lambda^{2}}+\frac{2 b}{\lambda}+b^{2} \tag{7}
\end{align*}
$$

Replacing expression (2) and (7) into expression (1):

$$
\begin{align*}
\theta_{x} & =\sqrt{\left(\frac{2}{\lambda^{2}}+\frac{2 b}{\lambda}+b^{2}\right)-\left(\frac{1}{\lambda}+b\right)^{2}} \\
& =\sqrt{\left(\frac{2}{\lambda^{2}}+\frac{2 b}{\lambda}+b^{2}\right)-\left(\frac{1}{\lambda^{2}}+\frac{2 b}{\lambda}+b^{2}\right)} \\
& =\frac{1}{\lambda}
\end{align*}
$$

### In conclusion, the standard deviation of $X$ is $\sigma_{x}=\frac{1}{\lambda}$.    

#### (3) i) Cumulative distribution function (CDF): Considering the definition of CDF, it follows that:

$$
\begin{equation*}
F_{x}(x)=P(x \leqslant x)=\int_{-\infty}^{\infty} p_{x}(t) d t . \tag{1}
\end{equation*}
$$

If $x<b$, then $p_{x}(t)=0$, thus there is:

$$
\begin{equation*}
F_{X}(x)=\int_{-\infty}^{x^{\prime}} 0 d t=0 \tag{2}
\end{equation*}
$$

If $x \geqslant b$, then $p_{x}(t)=\lambda e^{-\lambda(t-b)}$, thus there is:

$$
\begin{equation*}
F_{x}(x)=\int_{b}^{x} \lambda e^{-\lambda(t-b)} d t \tag{3}
\end{equation*}
$$

Assuming that $a=t-b$, then $t=u+b$. and $d t=d u$, the upper and Cower limit of integration becomes $0 \rightarrow x-b$.

$$
\begin{aligned}
F_{x}(x) & =\int_{0}^{x-b} \lambda e^{-\lambda u} d u \\
& =\lambda \cdot \int_{0}^{x-b} e^{-\lambda u} d u \\
& =\lambda\left[-\frac{1}{\lambda} e^{-\lambda u}\right]_{0}^{x-b} \\
& =\lambda \cdot\left(-\frac{1}{\lambda} e^{-\lambda(x-b)}+\frac{1}{\lambda} e^{0}\right) \\
& =\lambda \cdot\left(-\frac{1}{\lambda} e^{-\lambda(x-b)}+\frac{1}{\lambda}\right)
\end{aligned}
$$

$$
\begin{equation*}
=-e^{-\lambda(x-b)}+1 \tag{4}
\end{equation*}
$$

### In conclusion, the cumulative distribution function for the random variable $x$ is $F_{x}(x)= \begin{cases}0, & \text { if } x<b \\ 1-e^{-x(x-b)}, & \text { if } x \geqslant b\end{cases}$    


#### ii) Quartile Function (QF)

Considering the CDF of random variable $X$ :

$$
F_{X}(x)=\left\{\begin{array}{l}
0, \text { if } x<b  \tag{1}\\
1-e^{-\lambda(x-b),} \text { if } x \geqslant b
\end{array}\right.
$$

Quartile Function $Q(p)$ satisfies:

$$
\begin{equation*}
F_{x}(Q(p))=p \text {, if } 0<p<1 \tag{2}
\end{equation*}
$$

Replacing (1) into cl), it follows that:

$$
\begin{equation*}
1-e^{-\lambda(x-b)}=p \tag{3}
\end{equation*}
$$

Thus there is:

$$
\begin{equation*}
e^{-\lambda(x-b)}=1-p \tag{4}
\end{equation*}
$$

Taking the natural logarithm of both sides:

$$
\begin{equation*}
-\lambda(x-b)=\ln (1-p) \tag{5}
\end{equation*}
$$

Thus $x=b-\frac{\ln (1-p)}{\lambda}$
### In conclusion, the Quartile Function of random variable $X$ is $Q(p)=b-\frac{\ln (1-p)}{\lambda}, 0<p<1$    

#### (4) Maxmum Likehood estimat \MLE:

The definition of likehood function is:

$$
\begin{align*}
L(\lambda) & =\prod_{i=1}^{n} p_{\lambda}\left(x_{i}\right) \\
& =\prod_{i=1}^{n} \lambda e^{-\lambda\left(x_{i}-b\right)} \\
& =\lambda^{n} \prod_{i=1}^{n} e^{-\lambda\left(x_{i}-b\right)} \\
& =\lambda^{n} e^{-\lambda \sum_{i=1}^{n}\left(x_{i}-b\right)} \tag{1}
\end{align*}
$$

Taking the natural logarithm of both sides:

$$
\begin{equation*}
\ln L(\lambda)=n \ln \lambda-\lambda \sum_{i=1}^{n}\left(x_{i}-b\right) \tag{2}
\end{equation*}
$$

Derivativing with respect to $\lambda$ :

$$
\begin{equation*}
\frac{d \ln L(\lambda)}{d \lambda}=\frac{n}{\lambda}-\sum_{i=1}^{n}\left(x_{i}-b\right) \tag{3}
\end{equation*}
$$

Assuming that the derivative is zero, it follows that:

$$
\begin{equation*}
\frac{n}{\lambda}-\sum_{i=1}^{n}\left(x_{i}-b\right)=0 \tag{4}
\end{equation*}
$$

Calculating the value of $\lambda$ is:

$$
\begin{equation*}
\lambda=\frac{n}{\sum_{i=1}^{n}\left(x_{i-b}\right)} \tag{5}
\end{equation*}
$$

#### In conclusion, the maxmum likehood estimate for $x$ is $\lambda_{\text {OLE }}=\frac{n}{\sum_{i=1}^{n}\left(x_{i}-b\right)}$

